refactor: copy-data-from-server

diff --git a/bin/copy-data-from-server b/bin/copy-data-from-server
--- a/bin/copy-data-from-server
+++ b/bin/copy-data-from-server
@@ -10,37 +10,56 @@ if [[ -z $1 ]]; then
     exit 1
 fi
 
-if [[ ${ENV:?} = "prod" ]]; then
-    echo "[!] YOU ARE IN PRODUCTION"
+production_warning() {
+    if [[ ${ENV:?} = "prod" ]]; then
+        echo "[!] YOU ARE IN PRODUCTION"
 
-    read -rp "Are you sure you want to proceed? (yes/NO): " response
-    if [[ $response != "yes" ]]; then
-        echo "Operation aborted."
-        exit 1
+        read -rp "Proceed with the copy of $dir_to_copy? (yes/NO): " response
+        if [[ $response != "yes" ]]; then
+            echo "Operation aborted."
+            exit 1
+        fi
     fi
-fi
+}
+
+compress_remote_dir() {
+    echo "Compressing '$dir_to_copy' in the remote server..."
+    # shellcheck disable=SC2029
+    ssh "$remote_host" "cd $server_data_dir && tar -zcf /tmp/$dir_to_copy.tgz $dir_to_copy"
+}
+
+download_compressed_copy() {
+    echo "Downloading '$dir_to_copy.tgz'..."
+    scp "$remote_host:/tmp/$dir_to_copy.tgz" "/tmp/$dir_to_copy.tgz"
+}
+
+delete_copy_from_remote() {
+    echo "Deleting remote '$dir_to_copy.tgz'..."
+    # shellcheck disable=SC2029
+    ssh "$remote_host" "rm /tmp/$dir_to_copy.tgz"
+}
+
+extract_locally() {
+    mkdir -pv "$local_data_dir/$dir_to_copy"
+    echo "Extracting '$dir_to_copy.tgz' locally..."
+    tar -zxf "/tmp/$dir_to_copy.tgz" -C "$local_data_dir"
+
+}
+
+delete_local_compressed_copy() {
+    rm "/tmp/$dir_to_copy.tgz"
+}
 
 dir_to_copy="$1"
 remote_host="${SERVER_USER:?}@${SERVER_HOST:?}"
 server_data_dir="${SERVER_DATA_DIR:?}"
 local_data_dir="${DATA_DIR:?}"
 
-echo "Compressing '$dir_to_copy' in the remote server..."
-# shellcheck disable=SC2029
-ssh "$remote_host" "cd $server_data_dir && tar -zcf /tmp/$dir_to_copy.tgz $dir_to_copy"
-
-echo "Downloading '$dir_to_copy.tgz'..."
-scp "$remote_host:/tmp/$dir_to_copy.tgz" "/tmp/$dir_to_copy.tgz"
-
-echo "Deleting remote '$dir_to_copy.tgz'..."
-# shellcheck disable=SC2029
-ssh "$remote_host" "rm /tmp/$dir_to_copy.tgz"
-
-mkdir -pv "$local_data_dir/$dir_to_copy"
-
-echo "Extracting '$dir_to_copy.tgz' locally..."
-tar -zxf "/tmp/$dir_to_copy.tgz" -C "$local_data_dir"
-
-rm "/tmp/$dir_to_copy.tgz"
+production_warning
+compress_remote_dir
+download_compressed_copy
+delete_copy_from_remote
+extract_locally
+delete_local_compressed_copy
 
 echo "Done."
